sudo: false
language: node_js

matrix:
  include:
  - node_js: 8
  - node_js: 10

script:
  - npm run lint
  - xvfb-run npm run test
  - npm run coverage

after_success:
  - npm run coverage-publish

addons:
  firefox: 'latest'
