name: libp2p-nodetrust-server
version: 0.0.1
summary: Server for libp2p nodetrust
description: Server for libp2p nodetrusts
confinement: strict
grade: stable

apps:
  libp2p-nodetrust-server:
    command: libp2p-nodetrust-server
    plugs: [network, network-bind]

parts:
  server:
    plugin: nodejs
    node-engine: 10.10.0
    source: server
